version: "3"
services:

  phpinfo:
    build: ./
    container_name: trial_php
    ports:
      - "18080:80"
    networks:
      - djnet
    volumes:
      - .:/var/www/html
    links:
      - mysqldb
    environment:
      ENVIRONMENT: dev 
      DB_HOST: mysql:host=mysqldb:3306;dbname=
      DB_NAME: trial_db
      DB_USER: djuser
      DB_PASSWORD: djpassword
      BASE_PATH: http://localhost:18080/

  mysqldb:
    container_name: trial_mysqldb
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - djnet
    restart: always
    environment:
      MYSQL_DATABASE: trial_db
      MYSQL_USER: djuser
      MYSQL_PASSWORD: djpassword
      MYSQL_ROOT_PASSWORD: rootdj

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: trial_phpmyadmin
    links:
      - mysqldb
    ports:
      - 8183:80
    networks:
      - djnet
    environment:
      PMA_HOST: mysqldb
      PMA_USER: djuser
      PMA_PASSWORD: djpassword
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 200M

networks:
    djnet:
        driver: bridge
